services:
  postgres:
    image: postgres:16
    container_name: erpsys_online_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: erpsys_online
      POSTGRES_USER: erpsys
      POSTGRES_PASSWORD: erpsys_password
    ports:
      - "5432:5432"
    volumes:
      - erpsys_online_postgres_data:/var/lib/postgresql/data

volumes:
  erpsys_online_postgres_data:
